<a href="https://colab.research.google.com/github/Donpm/tweeteval/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import sklearn
import numpy as np
import pandas as pd

In [4]:
# training data
train = pd.read_csv("/content/train_final.csv", encoding='latin1')

# test data
test = pd.read_csv("/content/test_final.csv", encoding='latin1')

In [5]:
train.head()

   id  label                                              tweet
0   1      0  @user Bono... who cares. Soon people will unde...
1   2      1  @user Eight years the republicans denied obama...
2   3      0  @user Get him some line help. He is gonna be j...
3   4      0               @user @user She is great. Hi Fiona!
4   5      1  @user She has become a parody unto herself? Sh...

In [6]:
test.tail()

        id                                              tweet
855  12772  #CNN irrationally argues 4 legalising #abortio...
856  12773  @user @user @user @user @user @user @user @use...
857  12774  #Conservatives dont care what you post..its ...
858  12775  #antifa #Resist.. Trump is trying to bring wor...
859  12776  #Maine you need to face facts @user doesnt re...

In [7]:
# non-racist/sexist related tweets
sum(train["label"] == 0)

7975

In [8]:
# racist/sexist related tweets
sum(train["label"] == 1)

3941

In [9]:
# check if there are any missing values
train.isnull().sum()
#train.isnull().values.any()

id       0
label    0
tweet    0
dtype: int64

In [10]:
#install tweet-preprocessor to clean tweets
!pip install tweet-preprocessor

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting tweet-preprocessor
  Downloading tweet_preprocessor-0.6.0-py3-none-any.whl (27 kB)
Installing collected packages: tweet-preprocessor
Successfully installed tweet-preprocessor-0.6.0

In [11]:
# remove special characters using the regular expression library
import re

#set up punctuations we want to be replaced
REPLACE_NO_SPACE = re.compile("(\.)|(\;)|(\:)|(\!)|(\')|(\?)|(\,)|(\")|(\|)|()|()|(\%)|($)|(\>)|(\<)|(\{)|(\})" )
REPLACE_WITH_SPACE = re.compile("(<br\s/><br\s/?)|(-)|(/)|(:).")

In [12]:
import preprocessor as p

# custum function to clean the dataset (combining tweet_preprocessor and reguar expression)
def clean_tweets(df):
  tempArr = []
  for line in df:
    # send to tweet_processor
    tmpL = p.clean(line)
    # remove puctuation
    tmpL = REPLACE_NO_SPACE.sub("", tmpL.lower()) # convert all tweets to lower cases
    tmpL = REPLACE_WITH_SPACE.sub(" ", tmpL)
    tempArr.append(tmpL)
  return tempArr

In [13]:
train_tweet = clean_tweets(train["tweet"])
train_tweet = pd.DataFrame(train_tweet)

In [14]:

# append cleaned tweets to the training data
train["clean_tweet"] = train_tweet

# compare the cleaned and uncleaned tweets
train.head(10)

,id,label,tweet,clean_tweet
0,1,0,@user Bono... who cares. Soon people will unde...,bono who cares soon people will understand tha...
1,2,1,@user Eight years the republicans denied obama...,eight years the republicans denied obamas pick...
2,3,0,@user Get him some line help. He is gonna be j...,get him some line help he is gonna be just fin...
3,4,0,@user @user She is great. Hi Fiona!,she is great hi fiona
4,5,1,@user She has become a parody unto herself? Sh...,she has become a parody unto herself she has c...
5,6,0,@user @user @user @user @user @user @user @use...,this is the vetsresistsquadron is bullshit the...
6,7,1,@user Your looking more like a plant #maga #wa...,your looking more like a plant
7,8,0,@user @user Lol. Except hes the most successf...,lol except hes the most successful president i...
8,9,0,@user Been a Willie fan since before most of y...,been a willie fan since before most of you wer...
9,10,0,@user Here's a link to my channel with a pleth...,heres a link to my channel with a plethora of ...

In [15]:
# clean the test data and append the cleaned tweets to the test data
test_tweet = clean_tweets(test["tweet"])
test_tweet = pd.DataFrame(test_tweet)
# append cleaned tweets to the training data
test["clean_tweet"] = test_tweet

# compare the cleaned and uncleaned tweets
test.tail()

,id,tweet,clean_tweet
855,12772,#CNN irrationally argues 4 legalising #abortio...,irrationally argues legalising in based on the...
856,12773,@user @user @user @user @user @user @user @use...,city of chicago democrat run with some of the ...
857,12774,#Conservatives dont care what you post..its ...,dont care what you postits propaganda
858,12775,#antifa #Resist.. Trump is trying to bring wor...,trump is trying to bring world peace not obst...
859,12776,#Maine you need to face facts @user doesnt re...,you need to face facts doesnt really represent...

In [16]:
from sklearn.model_selection import train_test_split

# extract the labels from the train data
y = train.label.values

# use 70% for the training and 30% for the test
x_train, x_test, y_train, y_test = train_test_split(train.clean_tweet.values, y, 
                                                    stratify=y, 
                                                    random_state=1, 
                                                    test_size=0.3, shuffle=True)

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
documents = ["This is Import Data's Youtube channel",
             "Data science is my passion and it is fun!",
             "Please subscribe to my channel"]

# initializing the countvectorizer
vectorizer = CountVectorizer()

# tokenize and make the document into a matrix
document_term_matrix = vectorizer.fit_transform(documents)

# check the result
pd.DataFrame(document_term_matrix.toarray(), columns = vectorizer.get_feature_names_out())

,and,channel,data,fun,import,is,it,my,passion,please,science,subscribe,this,to,youtube
0,0,1,1,0,1,1,0,0,0,0,0,0,1,0,1
1,1,0,1,1,0,2,1,1,1,0,1,0,0,0,0
2,0,1,0,0,0,0,0,1,0,1,0,1,0,1,0

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

# vectorize tweets for model building
vectorizer = CountVectorizer(binary=True, stop_words='english')

# learn a vocabulary dictionary of all tokens in the raw documents
vectorizer.fit(list(x_train) + list(x_test))

# transform documents to document-term matrix
x_train_vec = vectorizer.transform(x_train)
x_test_vec = vectorizer.transform(x_test)

In [21]:
from sklearn import svm
# classify using support vector classifier
svm = svm.SVC(kernel = 'linear', probability=True)

# fit the SVC model based on the given training data
prob = svm.fit(x_train_vec, y_train).predict_proba(x_test_vec)

# perform classification and prediction on samples in x_test
y_pred_svm = svm.predict(x_test_vec)

In [22]:
from sklearn.metrics import accuracy_score
print("Accuracy score for SVC is: ", accuracy_score(y_test, y_pred_svm) * 100, '%')

Accuracy score for SVC is:  75.13286713286713 %

In [23]:
prob

array([[0.54217165, 0.45782835],
       [0.46797682, 0.53202318],
       [0.69531227, 0.30468773],
       ...,
       [0.41974682, 0.58025318],
       [0.63210693, 0.36789307],
       [0.84268511, 0.15731489]])